# permissions for end users to edit cmds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cmd-editor-role
rules:
- apiGroups:
  - exec.github.com
  resources:
  - cmds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - exec.github.com
  resources:
  - cmds/status
  verbs:
  - get
