apiVersion: exec.github.com/v1alpha1
kind: Cmd
metadata:
  name: cmd-sample2
spec:
  command: echo hi
  selector:
    app: kafka
  keys:
  - kafka-broker0-78cf89d7d6-lf6sg
  ips:
  - 10.1.243.252
  - 1.2.3.4