apiVersion: exec.github.com/v1alpha1
kind: Cmd
metadata:
  name: cmd-sample
spec:
  command: |
    echo "this is example commnad"
    ls -al
    ifconfig
    echo "result of final job: $?" 
  selector:
    app: nginx
  keys:
  - nginx-sample
  ips:
  - 10.1.243.222
  - 1.2.3.4